### ISSUE TITLE
Удалять клиента при дисконнекте

### ISSUE THREAD

**Issue by nefyodovve** [dkotenko/zappy#13]
файл game.c 
функция lgc_player_gone()
добавить delete_player(get_player_by_id(player_nb));

Если добавить сейчас, то будет крашиться. Если не добавить, будет дабл фри после смерти отключившегося клиента.

**Comment by dkotenko** [comment]
почему будет крашиться?

**Comment by nefyodovve** [comment]
Пофиксил.
Крашилось потому что не чистились сохраненные команды и при дисконнекте и вызове delete_player(), после нее вызывалась команда для уже удаленного игрока.
