### ISSUE TITLE
Клиент выполняет "взять ресурс", ресурс есть на клетке, но клиент получает КО

### ISSUE THREAD

**Issue by dkotenko** [dkotenko/zappy#16]
![image](https://user-images.githubusercontent.com/46926204/140825300-b7a90288-63aa-4f38-b16f-1f2a6da3f170.png)

**Comment by dkotenko** [comment]
Выполнил тесткейс на стороне сервера, ресурс берется.
`[09.11.2021 01:01:04.491864] [INFO] logic: Setup world

CELL INFO
x: 9 | y: 9 |
Inventory: nourriture: 0 |linemate: 0 |deraumere: 2 |sibur: 1 |mendiane: 3 |phiras: 2 |thystame: 0 |
visitors_num: 1
visitors ids: 3 
GO

PLAYER INFO
Player: player_id: 3 | team_id: 5 | level: 1 | orient: 0 | is_egg: 0
Inventory: nourriture: 10 |linemate: 0 |deraumere: 0 |sibur: 0 |mendiane: 0 |phiras: 0 |thystame: 0 |
CURRENT PLAYER CELL:
CELL INFO
x: 9 | y: 9 |
Inventory: nourriture: 0 |linemate: 0 |deraumere: 2 |sibur: 1 |mendiane: 3 |phiras: 2 |thystame: 0 |
visitors_num: 1
visitors ids: 3

TURN LEFT

PLAYER INFO
Player: player_id: 3 | team_id: 5 | level: 1 | orient: 0 | is_egg: 0
Inventory: nourriture: 10 |linemate: 0 |deraumere: 0 |sibur: 0 |mendiane: 0 |phiras: 0 |thystame: 0 |
CURRENT PLAYER CELL:
CELL INFO
x: 9 | y: 8 |
Inventory: nourriture: 0 |linemate: 0 |deraumere: 0 |sibur: 0 |mendiane: 1 |phiras: 0 |thystame: 0 |
visitors_num: 1
visitors ids: 3

GO

PLAYER INFO
Player: player_id: 3 | team_id: 5 | level: 1 | orient: 3 | is_egg: 0
Inventory: nourriture: 10 |linemate: 0 |deraumere: 0 |sibur: 0 |mendiane: 0 |phiras: 0 |thystame: 0 |
CURRENT PLAYER CELL:
CELL INFO
x: 9 | y: 8 |
Inventory: nourriture: 0 |linemate: 0 |deraumere: 0 |sibur: 0 |mendiane: 1 |phiras: 0 |thystame: 0 |
visitors_num: 1
visitors ids: 3


CELL BEFORE TAKE

CELL INFO
x: 8 | y: 8 |
Inventory: nourriture: 0 |linemate: 1 |deraumere: 0 |sibur: 0 |mendiane: 0 |phiras: 0 |thystame: 0 |
visitors_num: 1
visitors ids: 3

TAKE LINEMATE

PLAYER INFO
Player: player_id: 3 | team_id: 5 | level: 1 | orient: 3 | is_egg: 0
Inventory: nourriture: 10 |linemate: 1 |deraumere: 0 |sibur: 0 |mendiane: 0 |phiras: 0 |thystame: 0 |
CURRENT PLAYER CELL:
CELL INFO
x: 8 | y: 8 |
Inventory: nourriture: 0 |linemate: 0 |deraumere: 0 |sibur: 0 |mendiane: 0 |phiras: 0 |thystame: 0 |
visitors_num: 1
visitors ids: 3

TESTS PASSED SUCCESSFULLY`

**Comment by dkotenko** [comment]
в кейсе со скрина предлагаю выполнить voir перед взятием предмета

**Comment by dkotenko** [comment]
@nefyodovve прошу заново прогнать кейс на клиенте, после исправления нумерации направлений все должно быть ок

**Comment by nefyodovve** [comment]
Проблема всё ещё присутствует
![image](https://user-images.githubusercontent.com/25212107/141287793-ecefbeed-92f2-42bf-aab4-bc97ae1750d9.png)

**Comment by dkotenko** [comment]
@nefyodovve можешь перед TAKE_OBJECT еще раз SEE выполнить?

**Comment by nefyodovve** [comment]
Ситуация следующая возникла:

![image](https://user-images.githubusercontent.com/25212107/141329619-f908069b-fdbb-4f1f-ac6a-fde0a22569c7.png)

```
exec Type.SEE 
result {mendiane, nourriture phiras, nourriture nourriture, deraumere sibur sibur}
(I want to take ['nourriture'] from 1)
exec Type.GO 
result ok
exec Type.TURN_LEFT 
result ok
exec Type.GO 
result ok
exec Type.TAKE_OBJECT nourriture
```

Исходный voir был очевидно послан из клетки с 1 мендианом. В ответ пришло, что в 1 клетке (слева) находится нуритур+фирас, в 3 (справа) - дераумер и два сибура. Но по карте видно, что лево-право перепутано

**Comment by dkotenko** [comment]
voir fixed
