### ISSUE TITLE
Ориентация работает с цифрами 0-3, надо 1-4

### ISSUE THREAD

**Issue by nefyodovve** [dkotenko/zappy#18]

**Comment by nefyodovve** [comment]
Пофиксил в https://github.com/dkotenko/zappy/commit/650a687e6c1c73c3c01c0b9673f477737be3c97e

@dkotenko проверь что ничего не сломал. Я твою логику поворота не очень осознал, поэтому написал свою

**Comment by dkotenko** [comment]
протестил движение с поворотами, всё ок
