### ISSUE TITLE
Неправильно считается источник звука

### ISSUE THREAD

**Issue by nefyodovve** [dkotenko/zappy#19]
![image](https://user-images.githubusercontent.com/25212107/141472197-f1021d66-80f8-406d-9754-67df473b0a6f.png)

Здесь:

1. Игрок 4 сказал "4 test"
2. Игрок 5 получил "message 1,4 test"
3. Игрок 5 сказал "5 test"
4. Игрок 4 получил "message 7,5 test"

Если игроки заходят встретиться, то 4 пойдёт вверх, а 5 пойдёт вниз.

(на скрине от позиции 5 игрока то низа карты 7 клеток)

**Comment by dkotenko** [comment]
игрок 5 получил неправильную сторону сообщения. Это баг
**"Если игроки заходят встретиться, то 4 пойдёт вверх, а 5 пойдёт вниз.

(на скрине от позиции 5 игрока то низа карты 7 клеток)"** - здесь про что, поясни @nefyodovve

**Comment by nefyodovve** [comment]
Имеется ввиду, что если 5 пойдёт вниз - то это очень далёкий путь до 4, т.к. по X расстояние = 7 вниз до низа карты + 4 от верха до 4.

**Comment by dkotenko** [comment]
broadcast fixed
