### ISSUE TITLE
Если карта не квадратная, падает в voir

### ISSUE THREAD

**Issue by nefyodovve** [dkotenko/zappy#23]
сервер запущен с параматерами `-x11 -y12`

Здесь функция передает cell равный нулю

```
print_voir_cell(player, game->map->cells[h][get_w(print_w)]);
```

Ошибка возникает если смотреть с краю карты

**Comment by dkotenko** [comment]
fixed

**Comment by nefyodovve** [comment]
@dkotenko 

`-x15 -y10`

Падает здесь в самом начале
![image](https://user-images.githubusercontent.com/25212107/143033981-a501cde9-4654-443d-b94c-cf7a161972b0.png)

y = 10
x = 0
game->map->cells[10] = 0x0

**Comment by dkotenko** [comment]
fixed
