### ISSUE TITLE
Иногда происхоит так, что сервер не отвечает клиенту на его команду.

### ISSUE THREAD

**Issue by nefyodovve** [dkotenko/zappy#26]
commit 81406ed (версия сервера по состоянию 47376f5)

[server.log](https://github.com/dkotenko/zappy/files/7622945/server.log)

`[30.11.2021 07:18:45.523104]` - клиент 8 отправил команду 'broadcast 22101 took 5_0_0_0_0_0_0', результат не был возвращён. По логу видно что вместо этого дважды выполнилась команда для 5 клиента, т.е. почему то номер клиента оказался не тот.

`[30.11.2021 07:18:47.614949]` - клиент 6 отправил команду 'prend nourriture', результат не был возвращён

Появившаяся в последствии строчка `[30.11.2021 07:18:45.593450] [DEBUG] client->pending_commands: -1` говорит о том, что что-то идёт не так.

**Comment by dkotenko** [comment]
исправлено в https://github.com/dkotenko/zappy/commit/9bbb16550580792d1d416351a150d1c03d4773da

**Comment by nefyodovve** [comment]
Не исправлена, проблема в другом. Изучаю
