### ISSUE TITLE
Checklist - action list

### ISSUE THREAD

**Issue by nefyodovve** [dkotenko/zappy#3]
>**Action list**
>There is a global action list using an insertion soft so that actions requiring the shortest execution time are at the beginning of the list ?

Звучит как полный бред. Тут сказано, что как будто мне нужно делать список из комманд, сортируя их по увеличению времени выполнения (бинарное дерево?). Однако тогда получится, что если юзер сначала нажал "взять предмет" (7/t), а потом "открыть инвентарь" (1/t), то по итогу он сначала откроет инвентарь, а потом возьмет предмет, и в инвентаре его не будет.

Либо я не понял что тут имеется ввиду.

**Comment by dkotenko** [comment]
предмета и так не будет в ответе, ведь предмет возьмется только через 7 тиков

**Comment by nefyodovve** [comment]
Почему не будет? Клиент ждет 7 тиков, поднимает предмет, (получает ответ), потом 1 тик, (получает ответ), открывает инвентарь, там все есть.

**Comment by nefyodovve** [comment]
Вроде как я осознал что здесь хотят.

Имеется ввиду, что если примерно одновременно клиент А выполняет команду 1/t и клиент Б выполняет команду 7/t, то на временном отрезке клиент А выполнит команду раньше Б. При большом количестве клиентов нужно добавлять в структуру команды по возрастанию метки времени выполнения, чтобы они выполнялись тогда, когда надо. 

Мое непонимание было вызвано тем, что я думал только в рамках 1 клиента.
