### ISSUE TITLE
Зацикливание в voir

### ISSUE THREAD

**Issue by vlanf** [dkotenko/zappy#31]
В какой-то момент времени список замыкается сам на себе и происходит вечный цикл (temp->next == temp)

![image](https://user-images.githubusercontent.com/25212107/145328684-b26e3ade-703e-4e7b-a9e9-ec176b86a3a4.png)

**Comment by vlanf** [comment]
Ну или падает

![image](https://user-images.githubusercontent.com/25212107/145350160-00ba2004-450a-44a0-bb77-3d7e2d0296fb.png)

**Comment by dkotenko** [comment]
логи есть?

**Comment by vlanf** [comment]
[log.txt](https://github.com/dkotenko/zappy/files/7685798/log.txt)

**Comment by vlanf** [comment]
Попробовал поставить в ft_lstpop добавить строчку 45 - не помогло 

![image](https://user-images.githubusercontent.com/25212107/145420268-4a8ae3fc-3e3a-45de-bd6a-b2023a34cf3f.png)


[log2.txt](https://github.com/dkotenko/zappy/files/7686061/log2.txt)

**Comment by vlanf** [comment]
![image](https://user-images.githubusercontent.com/25212107/145426172-3196714e-735d-4e0b-9033-ffa2c544eb95.png)
[log3.txt](https://github.com/dkotenko/zappy/files/7686438/log3.txt)

**Comment by vlanf** [comment]
Проблема на строчке 147.

![image](https://user-images.githubusercontent.com/25212107/145475410-e9bf5831-9403-41ff-b31e-55d219ed0363.png)


Для добавления в список команд используется та же самая нода, что и для списка визитёров. Из-за этого, при подключении 2 игрока той же команды, список визитёров для клетки первого игрока корраптится.
