### ISSUE TITLE
Протекает 

### ISSUE THREAD

**Issue by nefyodovve** [dkotenko/zappy#9]
```
leaks Report Version: 4.0
Process 83203: 1081 nodes malloced for 81 KB
Process 83203: 2 leaks for 96 total leaked bytes.

    2 (96 bytes) << TOTAL >>
      1 (48 bytes) ROOT LEAK: 0x7f9050c005f0 [48]
      1 (48 bytes) ROOT LEAK: 0x7f9050c008c0 [48]

```

Не знаю где, @dkotenko глянь в логике. У меня до мерджа не текло.

Чтобы воспроизвести:

Запускаем сервак под ликсами:
```
leaks -atExit -- ./server
```

Коннектимся как админ, останавливаем клиент: 
```
nc 127.0.0.1 9876
-> BIENVENUE
<- ADMIN
<- zappy
<- stop server
```

(Ctrl-C не сработает, т.к. leaks тоже вырубится)

**Comment by dkotenko** [comment]
![image](https://user-images.githubusercontent.com/46926204/140826068-9fe5e1b5-1240-4dfb-ba65-78554b290b01.png)
лики при инициализации игры отсутствуют
